### ISSUE TITLE
Tests do not passed.

### ISSUE THREAD

**Issue by Fengyixin-research** [sbrisard/janus#23]
Thanks for the authors' kind guides. However, when I want to implement the tests, it shows

`============================ test session starts ==============================
platform linux -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/fengyx/下载/janus-master, configfile: pytest.ini
plugins: anyio-2.2.0
collected 127 items / 6 errors / 121 selected                                  

==================================== ERRORS ====================================
____________ ERROR collecting tests/test_discrete_green_operator.py ____________
ImportError while importing test module '/home/fengyx/下载/janus-master/tests/test_discrete_green_operator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_discrete_green_operator.py:7: in <module>
    import janus.fft.serial as fft
janus/fft/__init__.py:64: in <module>
    from .serial._serial_fft import FFTW_ESTIMATE
janus/fft/serial/__init__.py:7: in <module>
    from ._serial_fft import create_real
E   ModuleNotFoundError: No module named 'janus.fft.serial._serial_fft'
______________________ ERROR collecting tests/test_fft.py ______________________
ImportError while importing test module '/home/fengyx/下载/janus-master/tests/test_fft.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_fft.py:4: in <module>
    import janus.fft.serial
janus/fft/__init__.py:64: in <module>
    from .serial._serial_fft import FFTW_ESTIMATE
janus/fft/serial/__init__.py:7: in <module>
    from ._serial_fft import create_real
E   ModuleNotFoundError: No module named 'janus.fft.serial._serial_fft'
____________________ ERROR collecting tests/test_greenop.py ____________________
ImportError while importing test module '/home/fengyx/下载/janus-master/tests/test_greenop.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_greenop.py:6: in <module>
    import janus.material.elastic.linear.isotropic as material
E   ModuleNotFoundError: No module named 'janus.material.elastic.linear.isotropic'
_______ ERROR collecting tests/test_isotropic_linear_elastic_material.py _______
ImportError while importing test module '/home/fengyx/下载/janus-master/tests/test_isotropic_linear_elastic_material.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_isotropic_linear_elastic_material.py:3: in <module>
    import janus.material.elastic.linear.isotropic as material
E   ModuleNotFoundError: No module named 'janus.material.elastic.linear.isotropic'
__________________ ERROR collecting tests/test_memory_leak.py __________________
ImportError while importing test module '/home/fengyx/下载/janus-master/tests/test_memory_leak.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_memory_leak.py:5: in <module>
    import janus.material.elastic.linear.isotropic as material
E   ModuleNotFoundError: No module named 'janus.material.elastic.linear.isotropic'
___________________ ERROR collecting tests/test_operators.py ___________________
ImportError while importing test module '/home/fengyx/下载/janus-master/tests/test_operators.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_operators.py:9: in <module>
    from janus.operators import AbstractOperator
E   ModuleNotFoundError: No module named 'janus.operators'
=========================== short test summary info ============================
ERROR tests/test_discrete_green_operator.py
ERROR tests/test_fft.py
ERROR tests/test_greenop.py
ERROR tests/test_isotropic_linear_elastic_material.py
ERROR tests/test_memory_leak.py
ERROR tests/test_operators.py
!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 6 errors in 0.29s ===============================
`
I am using the latest Anaconda embedded with python 3.8 on ubuntu 20.04, the installation is finished without errors. Thanks for any help.

**Comment by sbrisard** [comment]
Thank you for opening this issue. For some reason, installing Janus with

```
python setup.py install
```

fails (some links seem to be broken). However,

```
python setup.py develop --user
```

does work.

I have never really dug into this issue, since I am mostly using Janus in "develop" mode. I will keep this issue open as a reminder that this should be solved!

**Comment by cilia-1106** [comment]
Hello @fenfam & @sbrisard, 
Thanks for reporting issues and providing potential solutions!
Unfortunately, I encountered the same problem with @fenfam (6 errors). However, even though I followed the instructions @sbrisard provided to re-install Janus, the errors still exist. The changes are:

Original: E ModuleNotFoundError: No module named 'janus.fft.serial._serial_fft'
Present:  ImportError: DLL load failed while importing _serial_fft

and the number of errors was reduced to 5...(crying TAT)

So, did anyone else have similar experiences? And how did you solve the problem?

**Comment by cilia-1106** [comment]
Maybe I solved the problem! (though many warnings still exist)

Add the path of file "libfftw3-3.dll" to the PATH environment variables, then most parts of the test pass:
======== 20 failed, 3023 passed, 111 skipped, 82 warnings in 43.12s =============

However, the parts related to "TestBlockDiagonalLinearOperator2D" failed: (I don't know why yet)
![d9eccffae230448a95e5bf4b1e47993](https://user-images.githubusercontent.com/80507166/189305545-9d729ac5-378c-43c1-92c7-140f657243a9.jpg)
![a926cec965b320056683cb6ac563f95](https://user-images.githubusercontent.com/80507166/189306345-5ef75f9b-2534-4d41-b8ee-2f68d6b59b33.jpg)

Since most of them have passed, I guess the Janus could work now. If anyone solves the problem about "TestBlockDiagonalLinearOperator2D", welcome to tell me!

**Comment by hyharry** [comment]
on my linux system those tests also don't pass, but the max abs/rel difference error is very small, order of 1e-15, so i assume the code should work fine.
